### ISSUE TITLE
Dont' compile with MathNet.Numerics V 2.6.1.30

### ISSUE THREAD

**Issue by LeMoussel** [mathnet/mathnet-numerics-data#5]
Can not compile with  MathNet.Numerics V 2.6.1.30.
I got error on Build() function. There is no definition for this function.
eg : public static Matrix<T> ReadMatrix<T>(...)
return Matrix<T>.Build.SparseMatrixOfIndexed(...)

**Comment by cdrnet** [comment]
Yes, this is expected. The current master branch is for V3, while we keep the V2 branch for future work/patches etc targetting V2. If you check out V2 instead of master, it should compile against MathNet.Numerics V 2.6.1.30.

I'm leaving the item open until this is properly documented somewhere.

**Comment by LeMoussel** [comment]
OK.
Actually V3 is in alpha prerelease version.
Product version is V2.6.1

**Comment by cdrnet** [comment]
Closing since v3 has been released.
